POST http://localhost:3333/videos
Content-type: application/json


{
    "title": "video 01",
    "description": "Esse é o primeiro video",
    "duration": 180

}

###

GET http://localhost:3333/videos

